# The documentation is at http://goreleaser.com
# Release instructions
# 1) git tag -a 0.1.0-alpha.1 -m "Release 0.1.0-alpha-1"
# 2) goreleaser          //--skip-publish for dry-run

builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - 7

snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ incpatch .Version }}-dev-{{ .ShortCommit }}"

source:
  enabled: true

dockers:
- skip_push: false
  use: buildx
  goos: linux
  goarch: amd64
  extra_files: [.git, go.sum, go.mod, pkg, cmd, config.yaml]
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  image_templates:
  - "automatedhome/{{.ProjectName}}:{{ .Version }}-amd64"
  - "automatedhome/{{.ProjectName}}:latest-amd64"

- skip_push: false
  use: buildx
  goos: linux
  goarch: arm64
  extra_files: [.git, go.sum, go.mod, pkg, cmd, config.yaml]
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  image_templates:
  - "automatedhome/{{.ProjectName}}:{{ .Version }}-arm64"
  - "automatedhome/{{.ProjectName}}:latest-arm64"

- skip_push: false
  use: buildx
  goos: linux
  goarch: arm
  goarm: 7
  extra_files: [.git, go.sum, go.mod, pkg, cmd, config.yaml]
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm"
  image_templates:
  - "automatedhome/{{.ProjectName}}:{{ .Version }}-arm"
  - "automatedhome/{{.ProjectName}}:latest-arm"

docker_manifests:
- name_template: 'automatedhome/{{.ProjectName}}:{{ .Version }}'
  image_templates:
  - 'automatedhome/{{.ProjectName}}:{{ .Version }}-amd64'
  - 'automatedhome/{{.ProjectName}}:{{ .Version }}-arm64'
  - 'automatedhome/{{.ProjectName}}:{{ .Version }}-arm'
- name_template: 'automatedhome/{{.ProjectName}}:latest'
  image_templates:
  - 'automatedhome/{{.ProjectName}}:latest-amd64'
  - 'automatedhome/{{.ProjectName}}:latest-arm64'
  - 'automatedhome/{{.ProjectName}}:latest-arm'
