---
mappings:
  - device: "temp"
    circuit: "28FF0A9171150270"
    topic: "solar/temperature/in"
  - device: "temp"
    circuit: "28FF1A181515019F"
    topic: "solar/temperature/out"
  - device: "temp"
    circuit: "28FF4C30041503A7"
    topic: "tank/temperature/up"
  - device: "temp"
    circuit: "28FF4D15151501C6"
    topic: "heater/temperature/in"
  - device: "temp"
    circuit: "28FF5AF502150270"
    topic: "heater/temperature/out"
  - device: "temp"
    circuit: "287CECBF060000DA"
    topic: "climate/temperature/outside"
  - device: "temp"
    circuit: "28FF89DB06000034"
    topic: "climate/temperature/inside"