name: Go

on:
  push:
    branches: [master, main]
  pull_request:

env:
  golang-version: 1.18.0
  golangci-lint-version: v1.45.0

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go ${{ env.golang-version }}
      uses: actions/setup-go@v3.0.0
      with:
        go-version: ${{ env.golang-version }}

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ env.golangci-lint-version }}

    - name: Build
      run: make build
