name: goreleaser

on:
  push:
    branches: [master, main]
    tags: ['*']
  pull_request:
    branches: ['**']
  workflow_dispatch:

env:
  golang-version: 1.18.0
  goreleaser-version: v1.7.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.golang-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Actions from this point are happening only on repository branches (not on PRs)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GoReleaser Release
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name != 'pull_request'
        with:
          distribution: goreleaser
          version: ${{ env.goreleaser-version }}
          args: release --rm-dist -f .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push development images
        if: ${{ startsWith(github.ref, 'refs/tags/') != true && github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ github.repository }}:master